SELECT 
       [CustomerKey]
     --,[GeographyKey]
     --,[CustomerAlternateKey]
     --,[Title]
      ,[FirstName]
     --,[MiddleName]
      ,[LastName]
	  ,[FirstName] + '' + [LastName] AS [FullName]
     --,[NameStyle]
     --,[BirthDate]
     --,[MaritalStatus]
     --,[Suffix]
      , CASE [Gender] WHEN 'M' THEN 'Male' WHEN 'F' THEN 'Female' END AS Gender
     --,[EmailAddress]
     --,[YearlyIncome]
     --,[TotalChildren]
     --,[NumberChildrenAtHome]
     --,[EnglishEducation]
     --,[SpanishEducation]
     --,[FrenchEducation]
     --,[EnglishOccupation]
     --,[SpanishOccupation]
     --,[FrenchOccupation]
     --,[HouseOwnerFlag]
     --,[NumberCarsOwned]
     --,[AddressLine1]
     --,[AddressLine2]
     --,[Phone]
      ,[DateFirstPurchase]
     --,[CommuteDistance]
	  ,  g.city AS [Customer City] -- Joined in Customer City from Geography Table
  FROM [AdventureWorksDW2022].[dbo].[DimCustomer]
  LEFT JOIN dbo.dimgeography AS g ON g.geographykey = dbo.DimCustomer.geographykey 
  ORDER BY CustomerKey ASC -- Ordered List by CustomerKey
